/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontSpecialChar.c                                     *
* Font:        ËÎÌו                                                  *
* Height:      33                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  33                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Gin\Desktop\specialChar.txt            *
* Read pattern file: C:\Users\Gin\Desktop\SpecialChar.txt            *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFontSpecialChar;

/* Start of unicode area <Letterlike Symbols> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontSpecialChar_2103[128] = { /* code 2103, DEGREE CELSIUS */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ____XXXX,X_______,XXXXXX__,________,
  ____X___,X_____XX,XX____XX,________,
  ____X___,X____XX_,________,XXX_____,
  ____X___,X___XX__,________,_XX_____,
  _____XXX,___XX___,________,__X_____,
  ________,___XX___,________,__X_____,
  ________,__XX____,________,__X_____,
  ________,__XX____,________,__X_____,
  ________,__XX____,________,__X_____,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XXX___,________,________,
  ________,___XX___,________,________,
  ________,___XXX__,________,__X_____,
  ________,____XX__,________,_X______,
  ________,_____XXX,_______X,X_______,
  ________,______XX,XXXXXXXX,________,
  ________,________,XXXXX___,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontSpecialChar_8384[128] = { /* code 8384 */
  ________,________,________,________,
  ________,________,________,________,
  ________,___X____,____X___,________,
  ________,___XXX__,____XX__,________,
  ________,___X____,____X___,________,
  ________,___X____,____X___,___XX___,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,___X____,____X___,________,
  ________,___X____,____X___,________,
  ________,___X____,____X___,XX______,
  _____XXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,_______X,X_______,________,
  ________,_______X,X_______,X_______,
  _______X,XXXXXXXX,XXXXXXXX,XX______,
  _______X,X______X,X______X,X_______,
  _______X,X______X,X______X,X_______,
  _______X,X______X,X______X,X_______,
  _______X,XXXXXXXX,XXXXXXXX,X_______,
  _______X,X______X,X______X,X_______,
  _______X,X______X,X______X,X_______,
  _______X,XXXXXXXX,XXXXXXXX,X_______,
  _______X,X_____XX,_______X,________,
  ________,_X____XX,________,________,
  ________,__X___XX,________,________,
  ________,___X_XX_,________,________,
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  ________,__XXX_XX,XX______,________,
  ________,_XXX____,XXXXXX__,________,
  ______XX,X_______,__XXXXXX,XXXXX___,
  ____XX__,________,______XX,XXXX____,
  ________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontFontSpecialChar_CharInfo[2] = {
   {  32,  32,  4, acGUI_FontFontSpecialChar_2103 } /* code 2103 */
  ,{  32,  32,  4, acGUI_FontFontSpecialChar_8384 } /* code 8384 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSpecialChar_Prop2 = {
   0x8384 /* first character */
  ,0x8384 /* last character  */
  ,&GUI_FontFontSpecialChar_CharInfo[  1] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSpecialChar_Prop1 = {
   0x2103 /* first character */
  ,0x2103 /* last character  */
  ,&GUI_FontFontSpecialChar_CharInfo[  0] /* address of first character */
  ,&GUI_FontFontSpecialChar_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFontSpecialChar = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,33 /* height of font  */
  ,33 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFontSpecialChar_Prop1}
  ,28 /* Baseline */
  ,15 /* Height of lowercase characters */
  ,22 /* Height of capital characters */
};

